name: "Tests on macOS"

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Tests on macOS
    runs-on: macos-13
    if:  ${{ github.event_name == 'pull_request' || github.repository == 'PalamaraLab/threads' }}

    steps:
      - name: checkout repo & submodules
        uses: actions/checkout@v2

      - name: install system packages
        run: brew install boost eigen

      - name: make build directory
        run: mkdir build_dir

      - name: cmake configure
        run: cmake .. -DENABLE_TESTING=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_COMPILER=$(brew --prefix llvm@15)/bin/clang++ -DCMAKE_C_COMPILER=$(brew --prefix llvm@15)/bin/clang
        working-directory: build_dir

      - name: cmake build
        run: cmake --build . --parallel 2
        working-directory: build_dir

      - name: cmake test
        run: ctest --no-tests=error -j2 --output-on-failure
        working-directory: build_dir
