name: Diagnostic exclude macos # FIXME remove before merge

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  build_wheels_cloud:
    name: Diagnostic ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
          include:
          - os: ubuntu-22.04
            arch: auto64
            py-vers: cp310-*
            before-all: echo "BEFORE ALL ubuntu-22.04"
            is-macos: false
          - os: ubuntu-24.04
            arch: auto64
            py-vers: cp311-*
            before-all: echo "BEFORE ALL ubuntu-24.04"
            is-macos: false
          - os: macos-13
            arch: x86_64
            py-vers: cp312-*
            before-all: echo "BEFORE ALL macos-13"
            is-macos: true
          - os: macos-14
            arch: arm64
            py-vers: cp313-*
            before-all: echo "BEFORE ALL macos-14"
            is-macos: true

          is-private-pr:
            - ${{ github.repository != 'PalamaraLab/threads' && github.event_name == 'pull_request' }}

          exclude:
            - { is-private-pr: true }
            - { is-macos: true }

    steps:
      - name: report run
        run: |
          echo "*** PYTHON ${{ matrix.py-vers }}"
          echo "*** BEFORE-ALL ${{ matrix.before-all }}"
          echo "*** RUN ${{ matrix.os }}"

  upload_all:
    name: Fake upload
    runs-on: ubuntu-latest
    steps:
      - name: report upload
        run: |
          echo "*** UPLOAD ALL"