name: Diagnostic exclude macos # FIXME remove before merge

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  build_wheels_cloud:
    name: Diagnostic ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            arch: auto64
            py-vers: cp310-*
          - os: ubuntu-24.04
            arch: auto64
            py-vers: cp311-*
          - os: macos-13
            arch: x86_64
            py-vers: cp312-*
          - os: macos-14
            arch: arm64
            py-vers: cp313-*

    steps:
      - name: Skip macOS PR in private repo
        if: |
          github.repository == 'PalamaraLab/TDPBWT' &&
          github.event_name == 'pull_request' &&
          startsWith(matrix.os, 'macos')
        run: |
          echo "::warning title=Skipping::Job is skipped to preserve macOS resources"
          echo "github.repository: ${{ github.repository }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "matrix.os: ${{ matrix.os }}"
          echo "job.continue-on-error ${{ job.continue-on-error }}"
          echo "is macos: ${{ startsWith(matrix.os, 'macos') }}"
          exit 1

      - name: report run
        run: |
          echo "*** PYTHON ${{ matrix.py-vers }}"
          echo "*** RUN ${{ matrix.os }}"

  upload_all:
    name: Fake upload
    runs-on: ubuntu-latest
    steps:
      - name: report upload
        run: |
          echo "*** UPLOAD ALL"
