name: Diagnostic exclude macos # FIXME remove before merge

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  build_wheels_cloud:
    name: Diagnostic ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            arch: auto64
            py-vers: cp310-*
          - os: ubuntu-24.04
            arch: auto64
            py-vers: cp311-*
          - os: macos-13
            arch: x86_64
            py-vers: cp312-*
          - os: macos-14
            arch: arm64
            py-vers: cp313-*

    steps:
      - name: Check if macOS build should be skipped
        if: |
          github.repository == 'PalamaraLab/TDPBWT' &&
          github.event_name == 'pull_request' &&
          startsWith(matrix.os, 'macos')
        run: |
          echo "::warning title=Skipping::Skipping job to preserve macOS resources"
          echo "SKIP_JOB=true" >> $GITHUB_ENV

      - name: checkout repo & submodules
        if: ${{ env.SKIP_JOB != 'true' }}
        run: echo "fake actions/checkout@v4"

      - name: Build wheels
        if: ${{ env.SKIP_JOB != 'true' }}
        run: echo "fake pypa/cibuildwheel@v2.22.0"

      - name: Upload
        if: ${{ env.SKIP_JOB != 'true' }}
        run: echo "fake actions/upload-artifact@v4"

  upload_all:
    name: Fake upload
    runs-on: ubuntu-latest
    steps:
      - name: report upload
        run: |
          echo "*** UPLOAD ALL"
