name: Regenerate snapshot data

on:
  workflow_dispatch:

jobs:
  build-and-run:
    name: Regenerate snapshot test data
    runs-on: ubuntu-24.04
    if: |
      (github.repository_visibility != 'private' || github.event_name == 'pull_request') &&
      !contains(github.event.pull_request.labels.*.name, 'ci:off')

    steps:
      - name: Checkout repo & submodules
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system packages
        run: |
          sudo apt -y update
          sudo apt -y install libboost-dev

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install cmake ninja

      - name: Install Threads with dev dependencies
        run: |
          pip install ".[dev]"

      - name: Display Python and library versions
        run: |
          python --version
          pip list

      - name: Regenerate snapshot data
        run: python test/regen_snapshot_data.py snapshot_out_dir

      - name: Upload archive files
        uses: actions/upload-artifact@v4
        with:
          name: regenerated-snapshot-data
          path: |
            snapshot_out_dir/expected_infer_snapshot.threads
            snapshot_out_dir/expected_convert_snapshot.argn
            snapshot_out_dir/expected_mapping_snapshot.mut
            snapshot_out_dir/expected_impute_snapshot.vcf
